LICENSE
Update license based on advice from Workiva's legal team.
=> EPL-6502 chore(package): update license and copyright info

pubspec.yaml
Pulls Included in Release:
* [EPL-6511: Initial Workiva json_schema release](https://github.com/Workiva/json_schema/pull/3)
Diff Between Last Tag and Proposed Release: N/A
Diff Between Last Tag and New Tag: N/A
=> EPL-6611 Release json_schema 1.0.8

analysis_options.yaml, bin/gensamples.dart, bin/schemadot.dart, example/from_json/movie_sample.dart, example/from_json/validate_json_from_data.dart, example/from_url/validate_instance_from_url.dart, lib/schema_dot.dart, lib/src/json_schema/browser/platform_functions.dart, lib/src/json_schema/format_exceptions.dart, lib/src/json_schema/json_schema.dart, lib/src/json_schema/schema_type.dart, lib/src/json_schema/type_validators.dart, lib/src/json_schema/utils.dart, lib/src/json_schema/validator.dart, lib/src/json_schema/vm/platform_functions.dart, test/unit/browser/json_schema/validation_test.dart, test/unit/vm/json_schema/invalid_schemas_test.dart, test/unit/vm/json_schema/validation_test.dart
- The main `JsonSchema` class is a large file, was pretty disorganized, and many of the functions contained within had a lot of side effects that made flow hard to follow. 
- Refactor some validations into a new file
- Rough alpha / category organization of the file
- Make validation flow more functional
=> EPL-7606: Reorganize JsonSchema Class

Dockerfile
In order to improve build isolation, reduce costs, reduce support burden, remove black magic, and improve local consistency, we are migrating away from smithy.yaml and existing Smithy infrastructure to Dockerfile builds supported by off the shelf AWS resources.
Reviewing and merging this PR is the first step in that process; this PR simply copies the contents of your smithy.yaml into a more explicit Dockerfile. 
In order to begin running Dockerfile builds you will need to enable Dockerfile builds from your [repo configuration page in Smithy](https://ci.webfilings.com/Workiva/json_schema.
Once you have enabled Dockerfile builds for your repo, rebuilding the PR build in smithy will trigger the newly enabled Dockefile build.
With only a [couple of …
=> Update Dockerfile to Mirror smithy.yaml

.travis.yml, lib/json_schema.dart, lib/src/json_schema/browser/platform_functions.dart, lib/src/json_schema/json_schema.dart, lib/src/json_schema/type_validators.dart, lib/src/json_schema/typedefs.dart, lib/src/json_schema/utils.dart, lib/src/json_schema/validator.dart, lib/src/json_schema/vm/platform_functions.dart, test/unit/vm/json_schema/validation_test.dart
- We have a suite of tests that isn't supported, but is needed (refRemote).
- Fix allthetests (woohoo! we have full spec support)
- merged master (Dockerfile support)
- ddev test
- CI
=> EPL-8649 feat(package): FULL draft 06 support

pubspec.yaml
Pulls Included in Release:
* [EPL-6666 feat(package): add semver_audit checks](https://github.com/Workiva/json_schema/pull/5)
* [BUILDTOOLS-2329: Update Dockerfile to mirror smithy.yaml](https://github.com/Workiva/json_schema/pull/10)
* [Update .gitignore to new `dart_tool` pub cache](https://github.com/Workiva/json_schema/pull/16)
* [af_new_drydock_image](https://github.com/Workiva/json_schema/pull/18)
* [fix a Completer's type](https://github.com/Workiva/json_schema/pull/22)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/1.0.8...Workiva:release_json_schema_1_0_9
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/1.0.8...1.0.9
The logs for the request that created this PR can be …
=> EPL-6673 Release json_schema 1.0.9

pubspec.yaml
Pulls Included in Release:
* [EPL-9779: 2.0.0 WIP](https://github.com/Workiva/json_schema/pull/21)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/1.0.9...Workiva:release_json_schema_2_0_0-RC1
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/1.0.9...2.0.0-RC1
=> EPL-9827 Release json_schema 2.0.0-RC1

pubspec.yaml
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.0.0-RC1...Workiva:release_json_schema_2_0_0-RC2
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.0.0-RC1...2.0.0-RC2
=> EPL-9829 Release json_schema 2.0.0-RC2

pubspec.yaml
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.0.0-RC3...Workiva:release_json_schema_2.0.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.0.0-RC3...2.0.0
=> WAP-1549 Release json_schema 2.0.0

pubspec.yaml
* [CPLAT-4192: Update json_schema to be Dart 2 compatible](https://github.com/Workiva/json_schema/pull/39)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.0.0...Workiva:release_json_schema_2.0.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.0.0...2.0.1
=> WAP-1552 Release json_schema 2.0.1

pubspec.yaml
* [WAP-2519: Support relative filesystem refs](https://github.com/Workiva/json_schema/pull/43)
* [WAP-2536: Address failing tests on Dart 2.2](https://github.com/Workiva/json_schema/pull/44)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.1.0...Workiva:release_json_schema_2.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.1.0...2.1.1
=> WAP-2432 Release json_schema 2.1.1

.travis.yml
=> WAP-2550 fix(package): update CI to target stable dart again

pubspec.yaml
* [WAP-2550 fix(package): update CI to target stable dart again](https://github.com/Workiva/json_schema/pull/46)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.1.1...Workiva:release_json_schema_2.1.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.1.1...2.1.2
=> WAP-2548 Release json_schema 2.1.2

pubspec.yaml
* [WAP-2520: Improve feedback on validation failures](https://github.com/Workiva/json_schema/pull/48)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.1.2...Workiva:release_json_schema_2.1.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.1.2...2.1.3
=> WAP-2551 Release json_schema 2.1.3

pubspec.yaml
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.1.3...Workiva:release_json_schema_2.1.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.1.3...2.1.4
=> WAP-2636 Release json_schema 2.1.4

CHANGELOG.md, pubspec.yaml
* Minor changes:
* [WAP-2881: Tweak error string for root level errors](https://github.com/Workiva/json_schema/pull/52)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.1.4...Workiva:release_json_schema_2.2.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.1.4...2.2.0
=> WAP-2776 Release json_schema 2.2.0

pubspec.yaml
* [CPLAT-6437: Prepare for upcoming change to HttpRequest and HttpClientResponse](https://github.com/Workiva/json_schema/pull/55)
* [CPLAT-6438: Fix TravisCI for Dart 1](https://github.com/Workiva/json_schema/pull/56)
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.2.0...Workiva:release_json_schema_2.2.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.2.0...2.2.1
=> WAP-2915 Release json_schema 2.2.1

lib/src/json_schema/constants.dart, lib/src/json_schema/json_schema.dart, lib/src/json_schema/type_validators.dart, lib/src/json_schema/utils.dart, lib/src/json_schema/validator.dart, pubspec.yaml, test/unit/vm/json_schema/validation_error_test.dart, test/unit/vm/json_schema/validation_test.dart
- We don't support draft 7.
- Run the draft 7 tests.
---
=> PROC-735 JSON Schema Draft 7 Support

MIGRATION.md, README.md, lib/src/json_schema/json_schema.dart
- Needed to update our readme's for new v3 changes
- Update MIGRATION.md
- Update README.md
- Update the comment on the public `refMap` getter.
N/A
N/A
---
=> PROC-876: V3 README Update

pubspec.yaml
* [CPLAT-7426 Run Dart 2 unit tests with dart2js](https://github.com/Workiva/json_schema/pull/60)
* [CPRO-358 fix(ref-resolution): Logic changes around remote ref resolution](https://github.com/Workiva/json_schema/pull/67)
* [WAP-9699: dart_dev upgrade](https://github.com/Workiva/json_schema/pull/69)
* [CPRO-350 Dart1 removal phase 2 and 3](https://github.com/Workiva/json_schema/pull/70)
* [CPRO-359: chore(package): update spec tests](https://github.com/Workiva/json_schema/pull/72)
* [PROC-709 fix(test): fix test cases involving formats](https://github.com/Workiva/json_schema/pull/73)
* [PROC-727 Ref Storage on Schemas and Path Resolution Changes](https://github.com/Workiva/json_schema/pull/74)
* [PROC-728: Fix Encoding and UTF-16 Spec …
=> PROC-877 Release json_schema 3.0.0

pubspec.yaml
* [Raise w_transport max to <5.0.0](https://github.com/Workiva/json_schema/pull/82)
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/3.0.0...Workiva:release_json_schema_3.0.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/3.0.0...3.0.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?pull_number=83&repo_name=Workiva%2Fjson_schema)
=> RM-103673 Release json_schema 3.0.1

lib/src/json_schema/json_schema.dart, lib/src/json_schema/utils.dart, pubspec.yaml
- json_pointer library is unmaintained.
- switch to rfc_6901
---
=> chore(package): switch to a json pointer lib that has null safety

lib/src/json_schema/json_schema.dart, test/unit/constants.dart
Key Words need implemented.
Copy and paste the some code until the spec tests pass.
Spec Tests passing.
---
=> Implement Dependent Schemas and Requiremets

test/unit/constants.dart
Our skipped test file list is disorganized.
Clean up our skipped test file list and document why things are skiiped.
Passing CI
---
=> Clean up and characterize skipped test files

lib/src/json_schema/json_schema.dart, lib/src/json_schema/validator.dart, test/unit/constants.dart
We would like unevaluatedItems implemented for draft2019 support.
Implement it.
---
=> Implement unevaluatedItems

lib/schema_dot.dart, pubspec.yaml, tool/cors_headers.dart, tool/serve_remotes.dart
wdesk has a hard constraint of `http = ^0.12.2` making json_schema 3.1 incompatible with wdesk
Downgrade `http`
---
=> chore(package): downgrade http dep

pubspec.yaml
* [chore(package): downgrade http dep](https://github.com/Workiva/json_schema/pull/114)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/3.1.0...Workiva:release_json_schema_3.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/3.1.0...3.1.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?pull_number=116&repo_name=Workiva%2Fjson_schema)
=> RM-130662 Release json_schema 3.1.1

lib/src/json_schema/json_schema.dart, lib/src/json_schema/validator.dart, test/unit/constants.dart
We should support the unevaluated properties keyword.
Create and implementation for the unevaluated properties keyword.
---
=> Implementation for unevaluated properties.

lib/src/json_schema/json_schema.dart, lib/src/json_schema/validator.dart, test/unit/constants.dart
Draft 2020 needs to support dynamic ref and dynamic anchors.
Implement them.
---
=> Implement Dynamic Refs and Dynamic Anchors for draft2020.

lib/src/json_schema/json_schema.dart, lib/src/json_schema/type_validators.dart, lib/src/json_schema/validator.dart, test/unit/json_schema/specification_test.dart
Using custom meta-schemas and vocabularies are difficult.
Refactor some code to pave the way for custom vocabularies.
---
=> Better Vocabulary Support

example/custom_vocabulary/custom_date_range.dart, example/custom_vocabulary/date-range-meta-schema.json, example/custom_vocabulary/example-date-range-schema.json, example/from_url/validate_instance_from_url.dart, lib/json_schema.dart, lib/src/json_schema/custom_vocabularies.dart, lib/src/json_schema/json_schema.dart, lib/src/json_schema/schema_url_client/html_schema_url_client.dart, lib/src/json_schema/schema_url_client/io_schema_url_client.dart, lib/src/json_schema/schema_url_client/schema_url_client.dart, lib/src/json_schema/type_validators.dart, lib/src/json_schema/typedefs.dart, lib/src/json_schema/validator.dart, test/additional_remotes/date-keyword-meta-schema.json, test/unit/json_schema/custom_vocabularies_test.dart
It sure would be nice to support custom vocabularies with validation.
Add some code to make it work.
---
=> Add custom vocabulary support

pubspec.yaml
* [SCM-759: Support 2020 12](https://github.com/Workiva/json_schema/pull/118)
* [Updated Pathing](https://github.com/Workiva/json_schema/pull/134)
* [SCM-798 feat(package): add support for custom formats](https://github.com/Workiva/json_schema/pull/135)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/3.2.1...Workiva:release_json_schema_4.0.0-rc.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/3.2.1...4.0.0-rc.2
This pull request can be recreated by clicking …
=> RM-134425 Release json_schema 4.0.0-rc.2

pubspec.yaml
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/4.0.0-rc.2...Workiva:release_json_schema_4.0.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/4.0.0-rc.2...4.0.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?pull_number=138&repo_name=Workiva%2Fjson_schema)
=> RM-135681 Release json_schema 4.0.0

lib/src/json_schema/json_schema.dart
type getter would throw when typeList was null
return null type when typeList is null
🤷
none
---
=> TASKPLAT-1105: support null typeList in type getter

pubspec.yaml
* [refactor: update to sound null safety](https://github.com/Workiva/json_schema/pull/143)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/4.0.4...Workiva:release_json_schema_5.0.0-rc1
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/4.0.4...5.0.0-rc1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?repo_name=Workiva%2Fjson_schema&pull_number=152)
=> RM-189801 Release json_schema 5.0.0-rc1

CHANGELOG.md
Changelog needs updating before we can publish our new version `5.0.0`
Updated the CHANGELOG.md file.
- N/A markdown file update only.
- N/A markdown file update only.
---
=> CUI-1729: Updated changelog for version 5.0.0-rc1.

pubspec.yaml
* [CUI-1729: Updated changelog for version 5.0.0-rc1.](https://github.com/Workiva/json_schema/pull/154)
Requested by: @kyleferguson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/5.0.0-rc1...Workiva:release_json_schema_5.0.0-rc2
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/5.0.0-rc1...5.0.0-rc2
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?repo_name=Workiva%2Fjson_schema&pull_number=155)
=> RM-194727 Release json_schema 5.0.0-rc2

pubspec.yaml
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/5.0.0-rc2...Workiva:release_json_schema_5.0.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/5.0.0-rc2...5.0.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?repo_name=Workiva%2Fjson_schema&pull_number=157)
=> RM-194918 Release json_schema 5.0.0

CHANGELOG.md, pubspec.yaml
* [Minor cleanup](https://github.com/Workiva/json_schema/pull/158)
* [feat(package): add empty constructor for convenience](https://github.com/Workiva/json_schema/pull/161)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/5.0.0...Workiva:release_json_schema_5.1.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/5.0.0...5.1.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?repo_name=Workiva%2Fjson_schem …
=> RM-196228 Release json_schema 5.1.0

example/custom_vocabulary/custom_date_range.dart, lib/src/json_schema/constants.dart, lib/src/json_schema/json_schema.dart, lib/src/json_schema/models/instance.dart, lib/src/json_schema/models/instance_ref_pair.dart, lib/src/json_schema/models/schema_path_pair.dart, lib/src/json_schema/models/schema_version.dart, lib/src/json_schema/models/validation_results.dart, lib/src/json_schema/schema_url_client/html_schema_url_client.dart, lib/src/json_schema/schema_url_client/io_schema_url_client.dart, lib/src/json_schema/utils/type_validators.dart, lib/src/json_schema/utils/utils.dart, lib/src/json_schema/validator.dart, test/unit/constants.dart, test/unit/json_schema/custom_vocabularies_test.dart, test/unit/json_schema/draft4_invalid_schemas_test.dart, test/unit/json_schema/specification_test.dart, tool/cors_headers.dart, tool/gen.dart
The package does not fulfill the linting guidelines on pub.dev at the moment, leading to a worse score than theoretically possible.
Using the recommended linting rules, I applied any suggestion that was applicable to the code base. Most suggestions were useful and an improvement regarding readability.
Tests and static analysis should still pass.
The changes might (have) lead to an external API change, which would not be desirable. 
---
=> Apply recommended linting rules

pubspec.yaml
* [Apply recommended linting rules](https://github.com/Workiva/json_schema/pull/160)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/5.1.0...Workiva:release_json_schema_5.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/5.1.0...5.1.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?repo_name=Workiva%2Fjson_schema&pull_number=165)
=> RM-197334 Release json_schema 5.1.1

pubspec.yaml
* [Update Changelog](https://github.com/Workiva/json_schema/pull/170)
* [Widen range of rfc_6901](https://github.com/Workiva/json_schema/pull/173)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/5.1.2...Workiva:release_json_schema_5.1.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/5.1.2...5.1.3
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?repo_name=Workiva%2Fjson_schema&pull_number=174)
=> RM-201970 Release json_schema 5.1.3

pubspec.yaml
* [Add a CODEOWNERS file](https://github.com/Workiva/json_schema/pull/177)
* [3546 Added publish workflow](https://github.com/Workiva/json_schema/pull/178)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/5.1.3...Workiva:release_json_schema_5.1.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/5.1.3...5.1.4
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?repo_name=Workiva%2Fjson_schema&pull_number=179)
=> RM-212468 Release json_schema 5.1.4

pubspec.yaml
* [Fix publish workflow](https://github.com/Workiva/json_schema/pull/180)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/5.1.4...Workiva:release_json_schema_5.1.5
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/5.1.4...5.1.5
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?repo_name=Workiva%2Fjson_schema&pull_number=181)
=> RM-251847 Release json_schema 5.1.5

pubspec.yaml
* [Fix names in publish workflow](https://github.com/Workiva/json_schema/pull/182)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/5.1.5...Workiva:release_json_schema_5.1.6
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/5.1.5...5.1.6
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?repo_name=Workiva%2Fjson_schema&pull_number=183)
=> RM-251856 Release json_schema 5.1.6

pubspec.yaml
* [Rewrite publish workflow to include --skip-validation flag](https://github.com/Workiva/json_schema/pull/185)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/5.1.6...Workiva:release_json_schema_5.1.7
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/5.1.6...5.1.7
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?repo_name=Workiva%2Fjson_schema&pull_number=186)
=> RM-251862 Release json_schema 5.1.7

lib/src/json_schema/models/validation_results.dart
Fix formatting error on master branch
None if CI passes
=> Fix formatting
