Workiva/json_schema

lib/src/json_schema/browser/platform_functions.dart
lib/src/json_schema/json_schema.dart
lib/src/json_schema/utils.dart
lib/src/json_schema/validator.dart
lib/src/json_schema/vm/platform_functions.dart
test/additional_remotes/bar.json
test/additional_remotes/string.json
test/additional_remotes/string_ref.json
test/unit/vm/json_schema/validation_test.dart

- The library doesn't resolve schema correctly when they have remote (read: http) `$ref`s nested within `properties` and other sub schemas, like `items` or `oneOf` / `anyOf` / `allOf`.
- When keyword refs also specify path fragments, they aren't resolved correctly.
Note: We don't yet handle refs within refs, further down the 🐇 🕳  we go in PR 3, stay tuned!
Blood, sweat, tears, and lots of recursion. 🤣 
- Pull down locally and run: `ddev format --check; ddev test`

EPL-7782: Allow Async Fetch of Refs Within Keywords + Resolve Fragments

---

lib/src/json_schema/schema.dart

Fix a strong mode at runtime issue, where a signature was declared to return a `Future<Schema>`, but at runtime we were returning a `Future<dynamic>`.
If this looks good, do you mind doing a package publish? This library is consumed by the Flutter command line tool, and a publish would help us make it strong mode clean. Thanks!

fix a Completer's type

---

lib/json_schema.dart
lib/src/json_schema/json_schema.dart
lib/src/json_schema/typedefs.dart
test/unit/vm/json_schema/validation_test.dart

- json_schema can only retrieve remote refs asynchronously from HTTP(S) URLs.
- allow the consumer to pass in sync and async ref providers.
- ddev test
- CI
- ref resolution

EPL-8486: Allow Consumers to Specify a Custom $ref Resolver

---

bin/schemadot.dart
example/from_url/validate_instance_from_url.dart
lib/json_schema.dart
lib/src/json_schema/schema.dart
pubspec.yaml
test/unit/vm/json_schema/invalid_schemas_test.dart
test/unit/vm/json_schema/validation_test.dart

SCREAMING CAPS constants have been removed as of Dart 2.0.0-dev.69.2 . This package will no longer work with any dev or stable releases going forward without fixes.
This PR uses the dart2_constant package to fix this in a way that is still backwards compatible with Dart 1. References to constants that have changed their names in Dart 2 are re-directed through the dart_constant package which uses pub version solving to back this with the appropriate SDK constants.
---

fix constants for dart 1 and dart 2 compat based off 1.0.9

---

bin/schemadot.dart
example/from_url/validate_instance_from_url.dart
lib/src/json_schema/constants.dart
lib/src/json_schema/json_schema.dart
lib/src/json_schema/vm/platform_functions.dart
pubspec.yaml
test/unit/vm/json_schema/invalid_schemas_test.dart
test/unit/vm/json_schema/validation_test.dart

SCREAMING CAPS constants have been removed as of Dart 2.0.0-dev.69.2 .  This package will no longer work with any dev or stable releases going forward without fixes.  
This PR uses the dart2_constant package to fix this in a way that is still backwards compatible with Dart 1.  References to constants that have changed their names in Dart 2 are re-directed through the dart_constant package which uses pub version solving to back this with the appropriate SDK constants.
---

Make compatible with Dart 1 and Dart 2 constant names

---

.travis.yml
Dockerfile

- sniping smithy-runner-generator
- use dart base image
- ensure CI / Travis passes
- 😕 
---
> __FYA:__ @michaelcarter-wf @travisreed-wf @dustinlessard-wf @bradbenjamin-wf

use dart base image

---

CHANGELOG.md
README.md
bin/gensamples.dart
bin/schemadot.dart
example/from_url/validate_instance_from_url.dart
example/readme/asynchronous_creation/from_file.dart
example/readme/asynchronous_creation/from_url.dart
example/readme/asynchronous_creation/geo.schema.json
example/readme/asynchronous_creation/remote_http_refs.dart
example/readme/asynchronous_creation/remote_ref_cache.dart
example/readme/synchronous_creation/local_ref_cache.dart
example/readme/synchronous_creation/self_contained.dart
lib/MIGRATION.md
lib/json_schema.dart
lib/schema_dot.dart
lib/src/json_schema/browser/platform_functions.dart
lib/src/json_schema/constants.dart
lib/src/json_schema/json_schema.dart
lib/src/json_schema/schema_type.dart
lib/src/json_schema/type_validators.dart
lib/src/json_schema/typedefs.dart
lib/src/json_schema/validator.dart
lib/src/json_schema/vm/platform_functions.dart
test/unit/vm/json_schema/invalid_schemas_test.dart
test/unit/vm/json_schema/validation_test.dart

Need to cut a final 2.0 release, after having used it for a few weeks of testing.
- thoroughly review the spec, and check that we have all constituent properties (manual read of spec) and that they behave as specified (validated with official spec tests).
- add references to each dart getter to the official draft6 spec.
- deprecate unsupported functionality
- rename functions while we still have the chance (
- make the whole `JsonSchema` object serializable with dart's `JSON.encode` via a `toJson` method.
- ddev test
- read the docs and review for correctness, clarity, grammar, etc.
- Whole package, covered by spec tests

WAP-1507 Final 2.0 Cleanup and Documentation

---

pubspec.yaml

* [use dart base image](https://github.com/Workiva/json_schema/pull/32)
* [WAP-1507 Final 2.0 Cleanup and Documentation](https://github.com/Workiva/json_schema/pull/33)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.0.0-RC2...Workiva:release_json_schema_2.0.0-rc3
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.0.0-RC2...2.0.0-RC3

EPL-10059 Release json_schema 2.0.0-RC3

---

.travis.yml
Dockerfile
analysis_options.yaml
lib/src/json_schema/json_schema.dart
lib/src/json_schema/utils.dart
pubspec.yaml
test/unit/vm/json_schema/validation_test.dart
tool/dev.dart

Update ```json_schema``` to be Dart 2 compatible.  
- None, but it might be worth running a few consumer tests. 
---
> __FYA:__ @michaelcarter-wf @corwinsheahan-wf @evanweible-wf @seanburke-wf @smaifullerton-wk

CPLAT-4192: Update json_schema to be Dart 2 compatible

---

pubspec.yaml

* [WAP-2264: Convenience getters around property names and required properties](https://github.com/Workiva/json_schema/pull/41)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.0.1...Workiva:release_json_schema_2.1.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.0.1...2.1.0

WAP-2350 Release json_schema 2.1.0

---

.travis.yml
lib/src/json_schema/json_schema.dart
lib/src/json_schema/utils.dart
test/relative_refs/root.json
test/relative_refs/string.json
test/relative_refs/subdir/integer.json
test/unit/vm/json_schema/validation_test.dart

`$ref` values to relative file paths were not resolving correctly
Made a couple of small tweaks to URL handling to ensure that relative paths are preserved, rather than turning into absolute URIs.
Tests added which should cover it.
N/A -- all tests pass.
---

WAP-2519: Support relative filesystem refs

---

test/unit/vm/json_schema/validation_test.dart

JSON parsing in Dart 2.2 changed for large numbers. On versions 2.1.1 and before (tested specifically on 1.24.3 & 2.1.1), the bignum inputs converted as follows:
```
JSON input: 12345678910111213141516171819202122232425262728293031
Dart value: 942084304541264551
```
while the conversion was wrong, tests in `bignum.json` only pertain to type checking, so they passed.
On the other hand, Dart 2.2 converts the same number like so:
```
JSON input: 12345678910111213141516171819202122232425262728293031
Dart value: 1.2345678910111214e+52
```
This is obviously more accurate, but Dart had to use a double type to represent a number this large. So the tests for integer types fail.
I decided that it's best to just skip these tests, for a few reasons:
1. Inconsistencies between Dart versions
2. Prior …

WAP-2536: Address failing tests on Dart 2.2

---

lib/src/json_schema/json_schema.dart

- `MapEquality` was used to check if 2 schema's were equal, which returns false if the schemas contain `enumValues`
- Use `DeepCollectionEquality` for comparing schema maps, as this will evaluate nested collections as well.
- Compare 2 separate yet identical schema's that contain `enumValues`.
- Schema comparing
---

WAP-2482: Use DeepCollectionEquality for hashcode and == operator

---

.travis.yml
CHANGELOG.md
dart_version.dart
lib/json_schema.dart
lib/src/json_schema/validator.dart
test/unit/vm/json_schema/validation_error_test.dart

Error strings were always prepending the instance path even when empty, leading to root level errors like this:
```
: required prop missing: id from {"foo": "bar"}
```
An empty path is correct for anything at the root level (see the [JSON Pointer](https://tools.ietf.org/html/rfc6901) spec), so this PR just removes the prepended colon if the instance path is empty.

WAP-2881: Tweak error string for root level errors

---

.travis.yml
Dockerfile

- Add a pub 1 get after pub 2 get
- Updating the version of Dart docker base image to be able to
- Install semver from a hosted pub server
- CI passes on Dart 1 now

CPLAT-6438: Fix TravisCI for Dart 1

---

bin/schemadot.dart
lib/src/json_schema/vm/platform_functions.dart

An upcoming change to the Dart SDK will change `HttpRequest` and
`HttpClientResponse` from implementing `Stream<List<int>>` to
implementing `Stream<Uint8List>`.
This forwards-compatible change prepares for that SDK breaking
change by casting the Stream to `List<int>` before transforming
it.
https://github.com/dart-lang/sdk/issues/36900
---

CPLAT-6437: Prepare for upcoming change to HttpRequest and HttpClientResponse

---

.travis.yml
pubspec.yaml

We'll soon be shipping unified Wdesk to production compiled with Dart 2/dart2js. Running the browser unit tests with the same compiler would increase our confidence in the code we're shipping to production.
- Updated CI to run the browser-based unit tests in production mode.
- Upgraded to a newer version of dependency_validator that automatically ignores some common dependencies used only for their binaries.
CI
---

CPLAT-7426 Run Dart 2 unit tests with dart2js

---

lib/src/json_schema/json_schema.dart
lib/src/json_schema/utils.dart
pubspec.yaml
test/unit/vm/json_schema/validation_test.dart

- We weren't passing some spec tests related to:
- UTF-16 encoding of the `pattern` property (regexes)
- JSON Pointer and URI encoding of property names in `definitions` / `properties` / custom properties
- Enable unicode on RegExp construction
- If searching for an encoded property name fails URI and JSON Pointer decode it and try again.
---

PROC-728: Fix Encoding and UTF-16 Spec Tests

---

pubspec.yaml
tool/dart_dev/config.dart

We're updating to w_transport v4. This is the first step to raise the upper bound. 2nd step will be to raise the lower bound.
Edit the pubspec to allow <5.0.0 for w_transport
Network calls that use w_transport
---

Raise w_transport max to <5.0.0

---

Makefile
README.md
pubspec.yaml
tool/dart_dev/config.dart

- dart_dev isn't null safe yet, and we use it very minimally
- remove the dependency in favor of a short Makefile
- update readme to make it more clear how to get started developing
---

fix(package): don't depend on dart_dev

---

lib/src/json_schema/type_validators.dart
lib/src/json_schema/utils.dart
lib/src/json_schema/validator.dart
test/unit/json_schema/deprecated/deprecated_globals_test.dart

- We had a custom json object comparison function in the lib
- Use deep collection equality instead.
---

imp(package): use standardized object comparison

---

README.md
bin/gensamples.dart
bin/schemadot.dart
example/from_json/movie_sample.dart
example/from_json/validate_json_from_data.dart
example/from_url/validate_instance_from_url.dart
example/readme/asynchronous_creation/from_file.dart
example/readme/asynchronous_creation/from_url.dart
example/readme/asynchronous_creation/remote_http_refs.dart
example/readme/asynchronous_creation/remote_ref_cache.dart
example/readme/synchronous_creation/local_ref_cache.dart
example/readme/synchronous_creation/self_contained.dart
lib/browser.dart
lib/json_schema.dart
lib/src/json_schema/global_platform_functions.dart
lib/src/json_schema/json_schema.dart
lib/src/json_schema/jsonata
lib/src/json_schema/ref_provider.dart
lib/src/json_schema/schema_url_client/html_schema_url_client.dart
lib/src/json_schema/schema_url_client/io_schema_url_client.dart
lib/src/json_schema/schema_url_client/schema_url_client.dart
lib/vm.dart
pubspec.yaml
test/unit/json_schema/draft4_invalid_schemas_test.dart
test/unit/json_schema/schema_self_validation.dart
test/unit/json_schema/validation_error_test.dart
test/unit/json_schema/validation_test.dart

- `JsonSchema.createSchema` is redundant
- `JsonSchema.createSchemaAsync` is redundant
- `JsonSchema.createSchemaFromUrl` is redundant
- No default implementation of a RefProvider exists for URLs.
- `RefProvider.syncSchema` is harder to use and worse than `RefProvider.syncJson`
- `RefProvider.asyncSchema` is harder to use and worse than `RefProvider.asyncJson`
- `JsonSchema.createSchema` --> `JsonSchema.create`
- `JsonSchema.createSchemaAsync` --> `JsonSchema.createAsync`
- `JsonSchema.createSchemaFromUrl` --> `JsonSchema.createFromUrl`
- Expose a `defaultUrlRefProvider`.
- `RefProvider.syncJson` --> `RefProvider.sync`
- `RefProvider.asyncJson` --> `RefProvider.async`
- Deprecate but allow all old factory names for `JsonSchema` and `RefProvider`
- Update all examples
- Update all usages
- …

imp(package): deprecate schema providers, rename top-level factories

---

lib/src/json_schema/validator.dart
test/unit/json_schema/validation_error_test.dart

- Consumers complain that it is difficult to tell which properties have required errors because we only expose them on the root object, and more detail would require parsing the error message.
- Expose an additional, more specific error.
- Test with workflow client validation before merging.
---

imp(validator): expose two errors for missing properties, one for the root object path, as well as the property itself

---

lib/src/json_schema/json_schema.dart
lib/src/json_schema/validator.dart
test/unit/constants.dart

`minContains` and `maxContains` is missing from draft 2019-09.
Implement the missing functionality.
Ensure the unit tests for minContains and maxContains pass for draft 2019-09.
---
> __FYA:__ @michaelcarter-wf @tomdeering-wf

Implement minContains and maxContains for draft 2019-09

---

lib/src/json_schema/json_schema.dart

Want to support `$defs`. Unfortunately we cannot enable its spec test yet, because that relies on being able to load the 2019 schema correctly in all its glory, and there are a number of obstacles to that.
---

Add basic untested $defs

---

lib/src/json_schema/json_schema.dart

Need to collect $contentEncoding and $contentSchema for draft 2019. Neither has bearing on validation.
Do it.
Passing CI
---

Implement $contentSchema, $contentEncoding Keywords

---

lib/src/json_schema/json_schema.dart
lib/src/json_schema/utils.dart
lib/src/json_schema/validator.dart
test/unit/constants.dart
test/unit/json_schema/specification_test.dart

Draft 2019 specifies properties can live beside `$refs`.
When there are additional properties alongside a `$ref`, mixin the `$ref` to the current object and remove the original `$ref` annotation.
---
> __FYA:__ @michaelcarter-wf @tomdeering-wf

Mixing JsonSchema objects to support properties along side of $refs

---

test/JSON-Schema-Test-Suite/README.md
test/JSON-Schema-Test-Suite/bin/jsonschema_suite
test/JSON-Schema-Test-Suite/remotes/draft-next/format-assertion-false.json
test/JSON-Schema-Test-Suite/remotes/draft-next/format-assertion-true.json
test/JSON-Schema-Test-Suite/remotes/draft-next/metaschema-no-validation.json
test/JSON-Schema-Test-Suite/tests/draft-next/optional/format-assertion.json
test/JSON-Schema-Test-Suite/tests/draft-next/vocabulary.json
test/JSON-Schema-Test-Suite/tests/draft2019-09/optional/format/unknown.json
test/JSON-Schema-Test-Suite/tests/draft2020-12/optional/format/unknown.json
test/JSON-Schema-Test-Suite/tests/draft4/optional/format/unknown.json
test/JSON-Schema-Test-Suite/tests/draft6/contains.json
test/JSON-Schema-Test-Suite/tests/draft6/optional/format/unknown.json
test/JSON-Schema-Test-Suite/tests/draft7/optional/format/unknown.json
test/unit/specification_remotes.dart
test/unit/specification_tests.dart

We always like to test against the most recent [spec tests](https://github.com/json-schema-org/JSON-Schema-Test-Suite). 
Particularly with Draft 2019 support nearing feature-completion, let's update again.
Passing CI
---

Update to latest JSON-Schema-Test-Suite

---

lib/src/json_schema/json_schema.dart

As of Draft 2019, `$definitions` and `$dependencies` remain reserved, but are no longer official keywords.
Ignore them
Passing CI
---

Ignore Old Keywords $definitions and $dependencies

---

CHANGELOG.md
pubspec.yaml

* [Raise Max Versions](https://github.com/Workiva/json_schema/pull/84)
* [Migrate to GitHub actions](https://github.com/Workiva/json_schema/pull/85)
* [chore(package): switch to a json pointer lib that has null safety](https://github.com/Workiva/json_schema/pull/86)
* [fix(package): don't depend on dart_dev](https://github.com/Workiva/json_schema/pull/87)
* [feat(package): remove the need for separate vm and browser imports, upgrade deps](https://github.com/Workiva/json_schema/pull/89)
* [imp(package): use standardized object comparison](https://github.com/Workiva/json_schema/pull/90)
* [imp(package): deprecate schema providers, rename top-level factories](https://github.com/Workiva/json_schema/pull/91)
* [chore(package): update standard …

RM-124999 Release json_schema 3.1.0

---

lib/src/json_schema/constants.dart

https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.appendix.B.1 recommends that `$ref` removal be done using `$def`s.
Do it that way instead
Passing CI
---

Switch subschema inlining to use $defs

---

lib/src/json_schema/constants.dart
lib/src/json_schema/json_schema.dart
lib/src/json_schema/validator.dart
test/unit/constants.dart

We need to implement support for (1) gathering the `$vocabulary` property of a schema, and (2) validating according to the vocabularies in use that we support.
Do it.
Passing CI
---

Implement $vocabulary Support

---

example/from_json/movie_sample.dart
example/from_json/validate_json_from_data.dart
example/from_url/validate_instance_from_url.dart
example/readme/asynchronous_creation/from_file.dart
example/readme/asynchronous_creation/from_url.dart
example/readme/asynchronous_creation/remote_http_refs.dart
example/readme/asynchronous_creation/remote_ref_cache.dart
example/readme/synchronous_creation/local_ref_cache.dart
example/readme/synchronous_creation/self_contained.dart
lib/schema_dot.dart
lib/src/json_schema/json_schema.dart
lib/src/json_schema/validator.dart
test/unit/json_schema/configurable_format_validation_test.dart
test/unit/json_schema/nested_refs_in_root_schema_test.dart
test/unit/json_schema/relative_file_uri_test.dart
test/unit/json_schema/schema_self_validation.dart
test/unit/json_schema/validation_error_test.dart

Our existing `validate` and `validateWithErrors` would be better as a `validateWithResults` method that is able to return warning errors, annotations, standard outputs, etc. to the caller. What the caller does with that information is up to them.
Add it and deprecate the old versions. 
Passing CI
---

Add validateWithResults, Deprecate Preexisting

---

CHANGELOG.md
pubspec.yaml

* [Add validateWithResults, Deprecate Preexisting](https://github.com/Workiva/json_schema/pull/119)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/3.1.1...Workiva:release_json_schema_3.2.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/3.1.1...3.2.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?pull_number=122&repo_name=Workiva%2Fjson_schema)

RM-130782 Release json_schema 3.2.0

---

lib/src/json_schema/json_schema.dart
lib/src/json_schema/typedefs.dart
lib/src/json_schema/validator.dart
test/custom/valid_schemas/draft2019-09/example.json
test/unit/specification_tests.dart

In draft 2019, properties along side refs aren't properly evaluated.
Change the reference loop detection. Previously if the `JsonSchema` node that was just resolved contained a `$ref`, it was immediately resolved. Loop detection also happened with in this code.
In draft2019, we need to evaluate other properties in the returned ref. In draft 2019 and later we return immediately to allow other properties beside the ref can be evaluated. There is also a new loop-detector that takes into account the data being processed. This should be more robust with the dynamic scoping in draft 2019 and 2020.
The code path for draft7 and earlier should be unchanged for resolving nested refs.
---

A failing test example.

---

lib/src/json_schema/utils.dart
lib/src/json_schema/validator.dart

`Object.hash` doesn't exist in Dart 2.13
Port the `Object.hash` implementation to this library to make this usable in earlier versions of dart.
---

Backport a hashing function from a newer dart.

---

lib/src/json_schema/constants.dart
lib/src/json_schema/json_schema.dart

With the 2019-09 and 2020-12 draft schemas, the library will miss loading the local version and attempt to load them from the network. 
Add some additional checks to make sure the local schemas can be loaded.
---

Make some changes so we can load baked in schemas from disk.

---

lib/src/json_schema/json_schema.dart
test/unit/json_schema/schema_create_test.dart

`JsonSchema._fromRootMap` is directly assigning to `_schemaMap`, which is typed as `Map<String, dynamic>`. `JsonSchema.create` and other constructors accept a `dynamic` input, and type check on `Map`. This allows for other types of Maps, e.g. `Map<dynamic, dynamic>`, that may contain acceptable data, but fail the type check.
Use `Map<String, dynamic>.from()` to iterate over the input map and create the correctly typed map. This also will prevent accidental mutations to the input map.
Unit test coverage should be sufficient.
---

Use Map.from() in JsonSchema._fromRootMap

---

lib/src/json_schema/json_schema.dart
test/unit/json_schema/resolve_path_test.dart

When resolving paths in a json schema in draft2019 and draft2020, the process will bail early if a ref is discovered. 
If there are still path segments when a ref is encountered, resolve the ref and continue on.
---

Initial try at fixing up resolving schemas at a path

---

lib/src/json_schema/json_schema.dart
test/unit/json_schema/resolve_path_test.dart
test/unit/json_schema/schema_create_test.dart
test/unit/json_schema/specification_test.dart

The `resolvePath` method skips over a `$ref` in the root of a JsonSchema object. It also throws an exception as soon as there is a JsonSchema object with a matching fragment and a `$ref`. Previous attempts to improve this behavior would cause certain schemas to throw cycle errors when none were present.
When there are still fragments to traverse, look down both paths. A path will either resolve or return an error. Memomize the results of path looks ups. Once a path has been looked up, no need to look it up agan.
---

Updated Pathing

---

CHANGELOG.md
pubspec.yaml

* [imp(json-schema): memoize hashCode and make schemaMap immutable](https://github.com/Workiva/json_schema/pull/139)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/4.0.0...Workiva:release_json_schema_4.0.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/4.0.0...4.0.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?pull_number=140&repo_name=Workiva%2Fjson_schema)

RM-135877 Release json_schema 4.0.1

---

pubspec.yaml

* [TASKPLAT-1105: support null typeList in type getter](https://github.com/Workiva/json_schema/pull/141)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/4.0.1...Workiva:release_json_schema_4.0.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/4.0.1...4.0.2
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?pull_number=142&repo_name=Workiva%2Fjson_schema)

RM-136241 Release json_schema 4.0.2

---

.github/CONTRIBUTING.md
Dockerfile

This Sourcegraph batch replaces deprecated commands from the Dart SDK with the new ones.
All new CLI commands now live under the main `dart` executable. See this issue for the details
https://github.com/dart-lang/sdk/issues/46100
This PR might need to be checked or tweaked for possible errors in the arguments to 
`dart analyze` and `dart format` since they take slightly different arguments than the original.
In most cases for analyze all the arguments can be removed and it can just be `dart analyze`.
Some of the argument changes were difficult to match and replace in an automated way. Since
there are only a few places that might break, it'll be easier to let the batch create the PR
and then manually adjust them.
`-w` should be removed automatically since overwriting files is now the …

Replace deprecated commands with new dart commands

---

lib/src/json_schema/json_schema.dart

For some reason, code using ListSlice sometimes triggers the following dart2js compiler bug: https://github.com/dart-lang/sdk/issues/48762
<details>
<summary>The error it produces (click to expand)</summary>
```
org-dartlang-app:///packages/collection/src/algorithms.dart@14383+1:
Internal Error: Runtime type information not available for type_variable_local(j:type_variable(quickSort.E)) in (SyntheticLocal(result), local(quickSort#elements), local(quickSort#compare), local(quickSort#start), local(quickSort#end)) for j:method(quickSort).
The compiler is broken.
When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.
The Dart team would greatly appreciate if you would …
```

CPLAT-17467 Remove usages of .slice to work around a dart2js compiler bug

---

.github/workflows/dart_ci.yaml
pubspec.yaml

This package isn't nullsafe yet so the dev and beta channels in the CI matrix are failing.
Remove those stages until we've updated to null safety. 
Also updates a few dependencies so that it resolves to a new enough test package that doesn't try to use the removed to level dart2js command line.
CI should pass without any failures now.

remove dart 3 from CI for now

---

.pubignore
CHANGELOG.md
pubspec.yaml

Perform some minor cleanup after the null migration
- remove the pre-release version of collection
- update logging dependency to ^1.0.0
- add a .pubignore to only publish relevant files

Minor cleanup

---

lib/src/json_schema/json_schema.dart
lib/src/json_schema/models/schema_version.dart
test/unit/json_schema/empty_schemas.dart

- Lots of people use empty schemas as a default somewhere
- Make it easier and also fast
---

feat(package): add empty constructor for convenience

---

pubspec.yaml

- Consumers need to be able to use json_schema with http 1.0
- Widen the range so that both sub-1 and 1.0 are supported.
---

chore(package): widen range on http

---

.github/workflows/publish.yaml

This PR addresses two problems:
- Publishing the SBOM as a release asset
- Automatically publishing to pub.dev

3546 Added publish workflow

---

.github/workflows/publish.yaml

Fix names in the publish workflow

Fix names in publish workflow

---

lib/src/json_schema/validator.dart
test/JSON-Schema-Test-Suite/tests/draft2020-12/unevaluatedProperties.json
test/unit/specification_tests.dart

Reported in #190, a property should count as evaluated if it's an `additionalProperty`.
Call `_addEvaluatedProp` when doing validation of an `additionalProperty`.
Added a test.
Are there cases where an additional property is validated where it _shouldn't_ count as evaluated?

Mark an `additionalProperty` as evaluated.

---

lib/src/json_schema/json_schema.dart

When running an application using json_schema with debugger, I tend to break on every exception. The json_schema initialization unnecessarily tried to parse the contents of `_fetchedFromUri`, which throws when this value is null.
I added an extra null check to avoid `JsonSchemaUtils.getBaseFromFullUri` call when the parameter is not given.
None identified.

Avoid unnecessary null pointer exception if reference schema is given

---

lib/src/json_schema/models/validation_results.dart

Bug described in #187: the `toString` of `ValidationResults` does not output errors or warnings due to flipped logic.
Flip the logic back!
Checked manually.
None.

Fix ValidationResults.toString().

---

CHANGELOG.md
pubspec.yaml

* [Avoid unnecessary null pointer exception if reference schema is given](https://github.com/Workiva/json_schema/pull/188)
* [Fix ValidationResults.toString().](https://github.com/Workiva/json_schema/pull/189)
* [Mark an `additionalProperty` as evaluated.](https://github.com/Workiva/json_schema/pull/191)
* [export ValidationResults](https://github.com/Workiva/json_schema/pull/192)
* [Fix formatting](https://github.com/Workiva/json_schema/pull/193)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/5.1.7...Workiva:release_json_schema_5.2.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/5.1.7...5.2.0
The logs for the request that created …

RM-252173 Release json_schema 5.2.0

---

lib/src/json_schema/validator.dart

`schemaPath` and `instancePath` on `ValidationError` is never `null`, so users shouldn't need to check for `null`.
`schemaPath` and `instancePath` was made non-nullable.
N/A.
nits:
* Users who access `schemaPath` or `instancePath` may get a warning, if they were doing null checks (most probably where). This warning is likely harmless and easy to fix by removing the unnecessary null check.
* Users who made a class that implements `ValidationError` may rely on `instancePath` and `schemaPath` being nullable.
However:
* It's unlikely that implementing `ValidationError` is common (the constructor is private, so it was probably not intended for subclassing).
* `ValidationError` should probably be a made a `final class ValidationError`.

Avoid nullable `schemaPath` and `instancePath`

---

.github/workflows/dart_ci.yaml
lib/fix_data.yaml
test_fixes/rename_to_validate.dart
test_fixes/rename_to_validate.dart.expect

These fixes will also show up as "quick fixes" in IDEs. Users do not need to run `dart fix --apply` manually.
**Example:**
```dart
import 'package:json_schema/json_schema.dart';
void main() {
final schema = JsonSchema.empty();
schema.validateWithResults(null);
final validator = Validator(schema);
validator.validateWithResults(null);
}
```
Will be updated by `dart fix --apply` to:
```dart
import 'package:json_schema/json_schema.dart';
void main() {
final schema = JsonSchema.empty();
schema.validate(null);
final validator = Validator(schema);
validator.validate(null);
}
```
`@Deprecated` message on `validateWithResults` was not automatically migrated.
Added `lib/fix_data.yaml` with [data driven fixes](https://github.com/flutter/flutter/blob/master/docs/contributing/Data-driven-Fixes.md#test- …

Add `lib/fix_data.yaml` for automatic migration with `dart fix`.
